# Generated by Django 3.2 on 2021-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user',
        ),
        migrations.AddField(
            model_name='user_info',
            name='profile_image',
            field=models.CharField(default=-1, max_length=9999),
            preserve_default=False,
        ),
    ]
