INSERT INTO home_cerealCategory (name) VALUES ('Heilsu'),
INSERT INTO home_cerealCategory (name) VALUES ('Sætt'),
INSERT INTO home_cerealCategory (name) VALUES ('Vegan')




INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Lucky Charms', 'General Mills' 'The cereal consists of toasted oat pieces and multi-colored marshmallow shapes', 2, 4.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Cocoa Puffs', 'General Mills', 'Chocolatey heaven', 2, 5.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Honey Nut Cheerios', 'General Mills', 'Honey flavored cheerios', 2, 3.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Capn Crunch Cranberries', 'Quaker Oats Company' 'Cranberry flavored capn crunch', 3, 6.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Bran Flakes', 'Kellogs', 'The cereal consists of toasted oat pieces and multi-colored marshmallow shapes', 1, 7.5, True, 20, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Cheerios', 'General Mills' 'The classic cheerios', 2, 4.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Frosted flakes', 'Kelloggs', 'Suger coated kornflakes', 2, 5.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Special K', 'Kelloggs', '', 2, 3.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Capn Crunch Cranberries','Grains,lightly toasted rice, wheat and barley','Quaker Oats Company' 'Cranberry flavored capn crunch', 3, 6.5, True, 0, Null)
INSERT INTO home_Cereal (name, manufacturer, description, category_id, price, inStock, onSale, total) VALUES ('Rice crispies', 'Kellogs', 'Puffed rice cereal', 1, 7.5, True, 20, Null)
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Jón Sigurðsson', 'Greniás 11', '210', 'Garðabær')
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Daníela Stefánsdóttir', 'Laugarásvegur 69', '104', 'Reykjavík'),
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Matthew McConaghey', 'Greenway 45', '90001', 'Los Angeles'),
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Binni Glee', 'Sundlaugabakki 4', '601', 'Akureyri'),
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Jónatan Sigþórs', 'Mýragata 43', '220', 'Hafnarfjörður'),
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Auddi Blö', 'Sjómannavegur 56', '551', 'Sauðárkrókur'),
INSERT INTO User_user_info (full_name, address, zip_code, town) VALUES ('Guðmundur Róbert', 'Króksnes 4', '580', 'Siglufjörður')

INSERT INTO User_SearchHistory (search, user_id) VALUES ('Lucky Charms', 1),
INSERT INTO User_SearchHistory (search, user_id) VALUES ('Cocoa Puffs', 1),
INSERT INTO User_SearchHistory (search, user_id) VALUES ('Capn Crunch', 2),
INSERT INTO User_SearchHistory (search, user_id) VALUES ('Honey Nut Cheerios', 5),
INSERT INTO User_SearchHistory (search, user_id) VALUES ('Bran Flakes', 3),
INSERT INTO User_SearchHistory (search, user_id) VALUES ('Rice Crispies', 4)

INSERT INTO User_country(country_name)
VALUES
('Afghanistan'),
('Albania'),
('Algeria'),
('Andorra'),
('Angola'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Australia'),
('Austria'),
('Austrian Empire'),
('Azerbaijan'),
('Baden*'),
('Bahamas, The'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bhutan'),
('Bolivia'),
('Bosnia Herzegovina'),
('Botswana'),
('Brazil'),
('Brunei'),
('Bulgaria'),
('Burkina'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Central African Rep'),
('Chad'),
('Chile'),
('China'),
('Colombia'),
('Comoros'),
('Congo'),
('Congo {Democratic Rep}'),
('Costa Rica'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czech Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('East Timor'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Fiji'),
('Finland'),
('France'),
('Gabon'),
('Gambia'),
('Georgia'),
('Germany'),
('Ghana'),
('Greece'),
('Grenada'),
('Guatemala'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Honduras'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland {Republic}'),
('Israel'),
('Italy'),
('Ivory Coast'),
('Jamaica'),
('Japan'),
('Jordan'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea North'),
('Korea South'),
('Kosovo'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macedonia'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Marshall Islands'),
('Mauritania'),
('Mauritius'),
('Mexico'),
('Micronesia'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montenegro'),
('Morocco'),
('Mozambique'),
('Myanmar, {Burma}'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Poland'),
('Portugal'),
('Qatar'),
('Romania'),
('Russian Federation'),
('Rwanda'),
('St Kitts & Nevis'),
('St Lucia'),
('Saint Vincent & the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome & Principe'),
('Saudi Arabia'),
('Senegal'),
('Serbia'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Sudan'),
('Spain'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Togo'),
('Tonga'),
('Trinidad & Tobago'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('United States'),
('Uruguay'),
('Uzbekistan'),
('Vanuatu'),
('Vatican City'),
('Venezuela'),
('Vietnam'),
('Yemen'),
('Zambia'),
('Zimbabwe')

VALUES
(1, 'Jón Sigurðsson', 'Greniás 11'),
(2, 'Daníela', 'Stefánsdóttir', 'Laugarásvegur 69'),
(3, 'Daníel', 'Tómasson', 'Lindaflöt 7'),
(4, 'Halldór', 'Atlason', 'Klettás 9'),
(5, 'Tómas', 'Jafetsson', 'Greniás 11'),
(6, 'Leó', 'Larsen', 'Drápuhlíð 14'),
(7, 'Halldór', 'Laxness', 'Gljúfrasteinn 1'),
(8, 'Matthew', 'Mcconaughey', 'Greenway 45'),
(9, 'Hildur', 'Stefánsdóttir', 'Brekkuás 4'),
(10, 'Jan', 'Vertongen', 'Oxford Street 4');
INSERT INTO User
VALUES
(1, 'Thjodarleidtoginn', 'Island123', 'jonsigurds@gmail.com', 'Greniás 11', 1),
(2, 'Danielabjorg', 'Tommi123', 'danielabjorg@gmail.com', 'Laugarásvegur 69', 2),
(3, 'LeoLarsen', 'Mamma321', 'leo_larsen@hotmail.com', 'Drápuhlíð 14', 6),
(4, 'HalliLax', 'brekkukotid123', 'halldorlaxness@outlook.com', 'Gljúfrasteinn 1', 7),
(5, 'mattycash', 'AlrightAlright12', 'matthew_mccon@gmail.com', 'Greenway 45', 8),
(6, 'HildurS', 'Brekkuas4', 'HildurStef@gmail.com', 'Brekkuás 4', 9),
(7, 'JanVertongen', 'Belgium123', 'janvertongen@gmail.com', 'Oxford Street 4', 10);

