# Generated by Django 3.2 on 2021-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_cartproduct_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartID',
            new_name='currentID',
        ),
        migrations.RemoveField(
            model_name='cereal',
            name='onSale',
        ),
        migrations.RemoveField(
            model_name='cerealimage',
            name='cereal',
        ),
        migrations.AddField(
            model_name='cereal',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cereal',
            name='image',
            field=models.ManyToManyField(to='home.cerealImage'),
        ),
        migrations.AddField(
            model_name='cereal',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cerealimage',
            name='path',
            field=models.CharField(default=-1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cereal',
            name='description',
            field=models.CharField(blank=True, max_length=1054),
        ),
        migrations.AlterField(
            model_name='cereal',
            name='inStock',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='cereal',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cereal',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
    ]
