# Generated by Django 3.2 on 2021-05-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210511_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cereal',
            old_name='inStock',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='cereal',
            name='image',
        ),
        migrations.AddField(
            model_name='cereal',
            name='image',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='home.cerealimage'),
            preserve_default=False,
        ),
    ]
