# Generated by Django 3.2.1 on 2021-05-14 21:21

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCardNumber', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('expiryDate', creditcards.models.CardExpiryField(verbose_name='expiration dae')),
                ('cvv', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
            ],
        ),
    ]
